import checkRobBased from "./specificAchievements/robBased";
import checkWizKhalifa from "./specificAchievements/wizKhalifa";
import checkKeyMouth from "./specificAchievements/keyMouth";
import checkBleachedGhouls from "./specificAchievements/paleKing";
import checkPower from "./specificAchievements/powerfulGhouls";
import checkPoolside from "./specificAchievements/checkPoolside";
import checkPositronic from "./specificAchievements/60Teraflops";
import checkDoodles from "./specificAchievements/doodle";
import checkLeverage from "./specificAchievements/moreLeverage";
import checkPurp from "./specificAchievements/purpByThePound";
import checkDustinsInferno from "./specificAchievements/dustinsInferno";
import checkMaximalism from "./specificAchievements/unhealthyMaximalism";
import checkHoodCrypto from "./specificAchievements/hoodCrypto";
import checkBasedTheRainbow from "./specificAchievements/basedTheRainbow";
import checkSomethingBorrowed from "./specificAchievements/checkSomethingBorrowed";
import checkSaints from "./specificAchievements/checkSaints";
import checkFloralShopping from "./specificAchievements/floralShopping";
import checkBasedVanHelsing from "./specificAchievements/basedVanHelsing";
import checkBasedDevelopmentCycle from "./specificAchievements/basedDevelopmentCycle";
import checkRoverDrivingClub from "./specificAchievements/roverDrivingClub";
import checkSomethingSpecialForThem from "./specificAchievements/somethingSpecialForThem";
import checkAtBothEnds from "./specificAchievements/atBothEnds";
import checkDungeonMaster from "./specificAchievements/dungeonMaster";
import checkSedoniacs from "./specificAchievements/sedoniac";
import checkTearsForFears from "./specificAchievements/tearsForFears";
import checkItAintEasyBeing from "./specificAchievements/itAintEasyBeing";
import checkHalloweenJack from "./specificAchievements/halloweenJack";
import checkStogie from "./specificAchievements/stogie";
import checkFrank from "./specificAchievements/letMeBeFrank";
import checkHopelessRomantic from "./specificAchievements/hopelessRomantic";
import checkTallAndFit from "./specificAchievements/everyoneLooksTallnFit";
import checkGreatness from "./specificAchievements/destinedForGreatness";
import checkUgly from "./specificAchievements/uglyAndLeaning";
import checkSecretSarge from "./specificAchievements/secretSarge";
import check420 from "./specificAchievements/420Somewhere";
import checkRosy from "./specificAchievements/checkRosyGhoul";
import checkCanto from "./specificAchievements/isThisCanto";
import checkBandages from "./specificAchievements/cantSeeDumping";
import checkSpecialEyes from "./specificAchievements/specialEyes";
import checkSleepyGhouls from "./specificAchievements/tiredInHere";
import checkRebaseRadio from "./specificAchievements/rebaseRadio";
import checkBlackness from "./specificAchievements/paintItBlack";
import checkCleanness from "./specificAchievements/cleanMachine";
import checkToxicity from "./specificAchievements/toxicAvenger";
import checkLungs from "./specificAchievements/noLungs";
import checkDirtiness from "./specificAchievements/dirtHead";
import checkUnholiness from "./specificAchievements/unholyCeremony";
import checkPyrophilia from "./specificAchievements/cryptoForPyros";
import checkHumanity from "./specificAchievements/realHumanBean";

export default function getValidAchievements(indices) {
    let achievements = {};
    achievements["Rob Based"] = checkRobBased(indices);
    achievements["Wiz Khalifa Special"] = checkWizKhalifa(indices);
    achievements["More Leverage"] = checkLeverage(indices);
    achievements["The Key is to..."] = checkKeyMouth(indices);
    achievements["The Pale King"] = checkBleachedGhouls(indices);
    achievements["No One Man Should Have All That Power"] = checkPower(indices);
    achievements["Blue Man Group"] = checkPoolside(indices);
    achievements["60 Teraflops"] = checkPositronic(indices);
    achievements["Purp by the Pound"] = checkPurp(indices);
    achievements["Dustin's Inferno"] = checkDustinsInferno(indices);
    achievements["/Tap to Achieve"] = (indices.size > 0) ? true : false;
    achievements["Unhealthy Maximalism"] = checkMaximalism(indices);
    achievements["Hood Crypto"] = checkHoodCrypto(indices);
    achievements["Based the Rainbow"] = checkBasedTheRainbow(indices);
    achievements["Something Borrowed"] = checkSomethingBorrowed(indices);
    achievements["A Guide To Recognizing Your Saints"] = checkSaints(indices);
    achievements["Floral Shopping"] = checkFloralShopping(indices);
    // achievements["That's Hoarding"] = false;
    achievements["Based Van Helsing"] = checkBasedVanHelsing(indices);
    achievements["Based Development Cycle"] = checkBasedDevelopmentCycle(indices);
    achievements["Do it for Doodle"] = checkDoodles(indices);
    achievements["Rover Driving Club"] = checkRoverDrivingClub(indices);
    achievements["Do Something Special For Them"] = checkSomethingSpecialForThem(indices);
    achievements["At Both Ends"] = checkAtBothEnds(indices);
    achievements["Dungeon Master"] = checkDungeonMaster(indices);
    achievements["Sedoniac"] = checkSedoniacs(indices);
    achievements["Tears for Fears"] = checkTearsForFears(indices);
    achievements["It Ain't Easy Being"] = checkItAintEasyBeing(indices);
    achievements["Halloween Jack is a Real Cool Cat"] = checkHalloweenJack(indices);
    achievements["Anywhere I Want"] = checkStogie(indices);
    achievements["Let Me Be Frank"] = checkFrank(indices);
    achievements["Hopeless Romantic"] = checkHopelessRomantic(indices);
    achievements["Everyone Looks Tall & Fit"] = checkTallAndFit(indices);
    achievements["Destined for Greatness"] = checkGreatness(indices);
    achievements["Ugly and Leaning Into It"] = checkUgly(indices);
    achievements["Secret Sarge"] = checkSecretSarge(indices);
    achievements["It's 4:20 Somewhere"] = check420(indices);
    achievements["By Any Other Name"] = checkRosy(indices);
    achievements["Is This Canto?"] = checkCanto(indices);
    // achievements["Rug Your Masters"] = false;
    achievements["Can't See Any Dumping"] = checkBandages(indices);
    achievements["Look With Your Special Eyes"] = checkSpecialEyes(indices);
    achievements["It's Tired in Here"] = checkSleepyGhouls(indices);
    achievements["Play it on My Radio"] = checkRebaseRadio(indices);
    achievements["Paint it Black"] = checkBlackness(indices);
    achievements["Clean Machine"] = checkCleanness(indices);
    achievements["Toxic Avenger"] = checkToxicity(indices);
    achievements["Ghouls Have No Lungs"] = checkLungs(indices);
    achievements["It's Called DIRT-head"] = checkDirtiness(indices);
    achievements["Unholy Ceremony"] = checkUnholiness(indices);
    achievements["Crypto for Pyros"] = checkPyrophilia(indices);
    achievements["Real Human Bean"] = checkHumanity(indices);
    return achievements;
}